// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sql} from '../models';
import {context} from '../models';
import {sqlx} from '../models';
import {driver} from '../models';
import {time} from '../models';

export function Begin():Promise<sql.Tx>;

export function BeginTx(arg1:context.Context,arg2:sql.TxOptions):Promise<sql.Tx>;

export function BeginTxx(arg1:context.Context,arg2:sql.TxOptions):Promise<sqlx.Tx>;

export function Beginx():Promise<sqlx.Tx>;

export function BindNamed(arg1:string,arg2:any):Promise<string>;

export function Close():Promise<void>;

export function Conn(arg1:context.Context):Promise<sql.Conn>;

export function Connx(arg1:context.Context):Promise<sqlx.Conn>;

export function Driver():Promise<driver.Driver>;

export function DriverName():Promise<string>;

export function Exec(arg1:string,arg2:Array<any>):Promise<sql.Result>;

export function ExecContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sql.Result>;

export function Get(arg1:any,arg2:string,arg3:Array<any>):Promise<void>;

export function GetContext(arg1:context.Context,arg2:any,arg3:string,arg4:Array<any>):Promise<void>;

export function MapperFunc(arg1:any):Promise<void>;

export function MustBegin():Promise<sqlx.Tx>;

export function MustBeginTx(arg1:context.Context,arg2:sql.TxOptions):Promise<sqlx.Tx>;

export function MustExec(arg1:string,arg2:Array<any>):Promise<sql.Result>;

export function MustExecContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sql.Result>;

export function NamedExec(arg1:string,arg2:any):Promise<sql.Result>;

export function NamedExecContext(arg1:context.Context,arg2:string,arg3:any):Promise<sql.Result>;

export function NamedQuery(arg1:string,arg2:any):Promise<sqlx.Rows>;

export function NamedQueryContext(arg1:context.Context,arg2:string,arg3:any):Promise<sqlx.Rows>;

export function Ping():Promise<void>;

export function PingContext(arg1:context.Context):Promise<void>;

export function Prepare(arg1:string):Promise<sql.Stmt>;

export function PrepareContext(arg1:context.Context,arg2:string):Promise<sql.Stmt>;

export function PrepareNamed(arg1:string):Promise<sqlx.NamedStmt>;

export function PrepareNamedContext(arg1:context.Context,arg2:string):Promise<sqlx.NamedStmt>;

export function Preparex(arg1:string):Promise<sqlx.Stmt>;

export function PreparexContext(arg1:context.Context,arg2:string):Promise<sqlx.Stmt>;

export function Query(arg1:string,arg2:Array<any>):Promise<sql.Rows>;

export function QueryContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sql.Rows>;

export function QueryRow(arg1:string,arg2:Array<any>):Promise<sql.Row>;

export function QueryRowContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sql.Row>;

export function QueryRowx(arg1:string,arg2:Array<any>):Promise<sqlx.Row>;

export function QueryRowxContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sqlx.Row>;

export function Queryx(arg1:string,arg2:Array<any>):Promise<sqlx.Rows>;

export function QueryxContext(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<sqlx.Rows>;

export function Rebind(arg1:string):Promise<string>;

export function Select(arg1:any,arg2:string,arg3:Array<any>):Promise<void>;

export function SelectContext(arg1:context.Context,arg2:any,arg3:string,arg4:Array<any>):Promise<void>;

export function SetConnMaxIdleTime(arg1:time.Duration):Promise<void>;

export function SetConnMaxLifetime(arg1:time.Duration):Promise<void>;

export function SetMaxIdleConns(arg1:number):Promise<void>;

export function SetMaxOpenConns(arg1:number):Promise<void>;

export function Stats():Promise<sql.DBStats>;

export function Unsafe():Promise<sqlx.DB>;
