// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['services']['BoletaService']['SetContext'](arg1);
}

export function Upload_file() {
  return window['go']['services']['BoletaService']['Upload_file']();
}
