// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Listar_Xmls() {
  return window['go']['services']['BoletaService']['Listar_Xmls']();
}

export function ReadXmls_folder() {
  return window['go']['services']['BoletaService']['ReadXmls_folder']();
}
