// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Listar_Xmls():Promise<any>;

export function ReadXmls_folder():Promise<any>;
