// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Buscar_trabajador(arg1) {
  return window['go']['services']['DashboardService']['Buscar_trabajador'](arg1);
}

export function Cumpleaños(arg1) {
  return window['go']['services']['DashboardService']['Cumpleaños'](arg1);
}

export function Regimenes_resumen() {
  return window['go']['services']['DashboardService']['Regimenes_resumen']();
}

export function Sexo_cantidad() {
  return window['go']['services']['DashboardService']['Sexo_cantidad']();
}
