// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Buscar_trabajador(arg1:string):Promise<any>;

export function Cumpleaños(arg1:number):Promise<any>;

export function Regimenes_resumen():Promise<any>;

export function Sexo_cantidad():Promise<any>;

export function Trabajadore_Activos_Area():Promise<any>;
