// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Buscar_trabajador(arg1) {
  return window['go']['services']['DashboardService']['Buscar_trabajador'](arg1);
}

export function Cumpleaños(arg1) {
  return window['go']['services']['DashboardService']['Cumpleaños'](arg1);
}

export function Reporte_Activos() {
  return window['go']['services']['DashboardService']['Reporte_Activos']();
}

export function Reporte_Organigrama(arg1) {
  return window['go']['services']['DashboardService']['Reporte_Organigrama'](arg1);
}

export function Reporte_Renuncias(arg1) {
  return window['go']['services']['DashboardService']['Reporte_Renuncias'](arg1);
}

export function Reporte_Sindicato(arg1) {
  return window['go']['services']['DashboardService']['Reporte_Sindicato'](arg1);
}

export function Resumen_Dashboard() {
  return window['go']['services']['DashboardService']['Resumen_Dashboard']();
}

export function Resumen_Regiemenes() {
  return window['go']['services']['DashboardService']['Resumen_Regiemenes']();
}

export function Trabajadore_Activos_Area() {
  return window['go']['services']['DashboardService']['Trabajadore_Activos_Area']();
}

export function Trabajadores_por_area(arg1) {
  return window['go']['services']['DashboardService']['Trabajadores_por_area'](arg1);
}
