// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Buscar_trabajador(arg1:string):Promise<any>;

export function Cumpleaños(arg1:number):Promise<any>;

export function Resumen_Dashboard():Promise<models.ResumenIndicadores>;

export function Trabajadore_Activos_Area():Promise<any>;

export function Trabajadores_por_area(arg1:string):Promise<any>;
