// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRenuncia(arg1, arg2) {
  return window['go']['services']['PersonalService']['AddRenuncia'](arg1, arg2);
}

export function Buscar_Areas(arg1) {
  return window['go']['services']['PersonalService']['Buscar_Areas'](arg1);
}

export function Buscar_Asistencia(arg1, arg2, arg3) {
  return window['go']['services']['PersonalService']['Buscar_Asistencia'](arg1, arg2, arg3);
}

export function Buscar_Cargos(arg1) {
  return window['go']['services']['PersonalService']['Buscar_Cargos'](arg1);
}

export function Buscar_dni_onlinne(arg1) {
  return window['go']['services']['PersonalService']['Buscar_dni_onlinne'](arg1);
}

export function Buscar_persona_by_dni(arg1) {
  return window['go']['services']['PersonalService']['Buscar_persona_by_dni'](arg1);
}

export function Crear_nuevoTrabajador(arg1, arg2) {
  return window['go']['services']['PersonalService']['Crear_nuevoTrabajador'](arg1, arg2);
}

export function EditByDni(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['PersonalService']['EditByDni'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Search_by_dni_vinculos(arg1) {
  return window['go']['services']['PersonalService']['Search_by_dni_vinculos'](arg1);
}
