// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Buscar_persona_by_dni(arg1) {
  return window['go']['services']['PersonalService']['Buscar_persona_by_dni'](arg1);
}
