// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRenuncia(arg1:models.Documento,arg2:number):Promise<void>;

export function Buscar_Areas(arg1:string):Promise<any>;

export function Buscar_Asistencia(arg1:string,arg2:number,arg3:number):Promise<any>;

export function Buscar_Cargos(arg1:string):Promise<any>;

export function Buscar_dni_onlinne(arg1:string):Promise<models.PersonDniRequest>;

export function Buscar_persona_by_dni(arg1:string):Promise<models.Perfil>;

export function Crear_nuevoTrabajador(arg1:models.Data,arg2:boolean):Promise<any>;

export function EditByDni(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function Search_by_dni_vinculos(arg1:string):Promise<any>;
